name: agency
channels:
- conda-forge
dependencies:
- python=3.6
- psychopy
- ipython
- jupyter
- pytorch
- pip
- pip:
  - psychtoolbox
  - pygame
  - pyparallel; platform_system != "Windows"
  - websocket_client
  - pyserial
  - pynput
  - pyro-ppl
